### ISSUE TITLE
consider modularizing APIs

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/oai-monarch-plugin#7]
Should we have

1. one plugin covering the entirety of the monarch API/KG
    - generic endpoint for multiple entity types
    - multiple endpoints
2. separate plugins for different types, e.g. disease, gene

My reading of the OAI docs suggest that 2 is best. This might be a bit more complicated for deployment, juggling multiple fastapi endpoints...

but perhaps the thing to do is focus on a disease endpoints; however, this may limit certain options such as chatgpt reasoning about how to chain multiple endpoints together (e.g. find all pairs of interacting genes in the same disease...)

**Comment by oneilsh** [comment]
I haven't tested it but I suspect the chaining could happen if both plugins are enabled. But that would mean users would have to know about the different plugins and actively choose to enable them though, so option 1 seems better to me. Which part of the docs are mentioning it?

I'm not sure about 1a vs 1b though - whether the model is better able to handle a few flexible endpoints, or more special purpose endpoints, I dunno.

**Comment by oneilsh** [comment]
Closing as we are live as of #45
