### ISSUE TITLE
deploy and register endpoint

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/oai-monarch-plugin#9]
Currently it's necessary to run this locally, which limits this to people who have chatGPT plugin advanced access

We should

1. [ ] deploy on a public server
2. [ ] register

we may want to delay 2 til we have figured out #7 

for 1, the q for monarch dev ops is

- given the server is so lightweight should we do using some serverless framework
- or it may be simplest to deploy alongside the main monarch fastapi

**Comment by cmungall** [comment]
do we have any further thoughts on how this might be done

**Comment by oneilsh** [comment]
see #28 and #29; RE #7 I will check the OpenAI review process, but I think a single Monarch plugin makes most sense and is working well in testing

**Comment by oneilsh** [comment]
Closing as we are live as of #45
